const express = require('express');
const app = express();
const port = 3000;

app.use(express.json());

const adiantamentoRoutes = require('./routes/adiantamentoRoutes');
const bonificacaoRoutes = require('./routes/bonificacaoRoutes');
const colaboradorRoutes = require('./routes/colaboradorRoutes');
const contatoRoutes = require('./routes/contatoRoutes');
const cpfRoutes = require('./routes/cpfRoutes');
const ctpsRoutes = require('./routes/ctpsRoutes');
const decimoTerceiroRoutes = require('./routes/decimoTerceiroRoutes');
const dependentesRoutes = require('./routes/dependentesRoutes');
const empresaRoutes = require('./routes/empresaRoutes');
const enderecoRoutes = require('./routes/enderecoRoutes');
const escalaRoutes = require('./routes/escalaRoutes');
const escolaridadeRoutes = require('./routes/escolaridadeRoutes');
const estadoCivilRoutes = require('./routes/estadoCivilRoutes');
const estadoRoutes = require('./routes/estadoRoutes');
const feriasRoutes = require('./routes/feriasRoutes');
const funcaoEmpresaRoutes = require('./routes/funcaoEmpresaRoutes');
const funcaoRegistroRoutes = require('./routes/funcaoRegistroRoutes');
const historicoSalarioRoutes = require('./routes/historicoSalarioRoutes');
const horasExtrasRoutes = require('./routes/horasExtrasRoutes');
const horasFaltasRoutes = require('./routes/horasFaltasRoutes');
const mesAnoRoutes = require('./routes/mesAnoRoutes');
const municipioRoutes = require('./routes/municipioRoutes');
const nacionalidadeRoutes = require('./routes/nacionalidadeRoutes');
const outrosAcrescimosRoutes = require('./routes/outrosAcrescimosRoutes');
const outrosDescontosRoutes = require('./routes/outrosDescontosRoutes');
const pagamentoRoutes = require('./routes/pagamentoRoutes');
const registroRoutes = require('./routes/registroRoutes');
const rescisaoRoutes = require('./routes/rescisaoRoutes');
const rgRoutes = require('./routes/rgRoutes');
const salarioVigenteRoutes = require('./routes/salarioVigenteRoutes');
const setoresRoutes = require('./routes/setoresRoutes');
const setorUsuarioRoutes = require('./routes/setorUsuarioRoutes');
const tipoDescAcresRoutes = require('./routes/tipoDescAcresRoutes');
const unidadeRoutes = require('./routes/unidadeRoutes');
const usuariosRoutes = require('./routes/usuariosRoutes');

app.use('/api/adiantamento', adiantamentoRoutes);
app.use('/api/bonificacao', bonificacaoRoutes);
app.use('/api/colaborador', colaboradorRoutes);
app.use('/api/contato', contatoRoutes);
app.use('/api/cpf', cpfRoutes);
app.use('/api/ctps', ctpsRoutes);
app.use('/api/decimo_terceiro', decimoTerceiroRoutes);
app.use('/api/dependentes', dependentesRoutes);
app.use('/api/empresa', empresaRoutes);
app.use('/api/endereco', enderecoRoutes);
app.use('/api/escala', escalaRoutes);
app.use('/api/escolaridade', escolaridadeRoutes);
app.use('/api/estado_civil', estadoCivilRoutes);
app.use('/api/estado', estadoRoutes);
app.use('/api/ferias', feriasRoutes);
app.use('/api/funcao_empresa', funcaoEmpresaRoutes);
app.use('/api/funcao_registro', funcaoRegistroRoutes);
app.use('/api/historico_salario', historicoSalarioRoutes);
app.use('/api/horas_extras', horasExtrasRoutes);
app.use('/api/horas_faltas', horasFaltasRoutes);
app.use('/api/mes_ano', mesAnoRoutes);
app.use('/api/municipio', municipioRoutes);
app.use('/api/nacionalidade', nacionalidadeRoutes);
app.use('/api/outros_acrescimos', outrosAcrescimosRoutes);
app.use('/api/outros_descontos', outrosDescontosRoutes);
app.use('/api/pagamento', pagamentoRoutes);
app.use('/api/registro', registroRoutes);
app.use('/api/rescisao', rescisaoRoutes);
app.use('/api/rg', rgRoutes);
app.use('/api/salario_vigente', salarioVigenteRoutes);
app.use('/api/setores', setoresRoutes);
app.use('/api/setor_usuario', setorUsuarioRoutes);
app.use('/api/tipo_desc_acres', tipoDescAcresRoutes);
app.use('/api/unidade', unidadeRoutes);
app.use('/api/usuarios', usuariosRoutes);

app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}/`);
});